
DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  lat FLOAT(8) NOT NULL,
  long FLOAT(8) NOT NULL,
  zoom INTEGER NOT NULL,
  created_on DATE NOT NULL,
  modified_on DATE NOT NULL
)
